# Generated by Django 6.1.1 on 2026-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('ru_value', models.TextField(blank=True)),
                ('uz_value', models.TextField(blank=True)),
            ],
        ),
    ]
