# Generated by Django 6.1.1 on 2026-09-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_translationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Chat ID for receiving leads', max_length=100, null=True),
        ),
    ]
