# Generated by Django 6.1.1 on 2026-09-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='demo_url',
            field=models.URLField(blank=True),
        ),
    ]
