# Generated by Django 6.1.1 on 2026-09-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_theme_demo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Answer (UZ)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Question (UZ)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author (UZ)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Quote (UZ)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role (UZ)'),
        ),
    ]
