# Generated by Django 6.1.1 on 2026-09-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faq_answer_uz_faq_question_uz_testimonial_author_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='category',
        ),
        migrations.DeleteModel(
            name='ThemeCategory',
        ),
    ]
