# Generated by Django 6.1.1 on 2026-09-21 06:51

from django.db import migrations, models


def backfill_order(apps, schema_editor):
    Theme = apps.get_model('core', 'Theme')
    for index, theme in enumerate(Theme.objects.order_by('id'), start=1):
        Theme.objects.filter(pk=theme.pk).update(order=index)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_theme_category_delete_themecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='theme',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order'),
        ),
        migrations.RunPython(backfill_order, migrations.RunPython.noop),
    ]
