# Generated by Django 6.1.1 on 2026-09-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_theme_options_theme_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this question on the site', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this testimonial on the site', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this theme on the site', verbose_name='Active'),
        ),
    ]
