# Generated by Django 6.1.1 on 2026-09-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_faq_is_active_testimonial_is_active_theme_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description (UZ)'),
        ),
    ]
