# Generated by Django 6.1.1 on 2026-09-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_theme_description_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (UZ)'),
        ),
    ]
