# Generated by Django 6.1.1 on 2026-09-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_theme_name_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('privacy', 'Privacy policy'), ('terms', 'Terms of use')], max_length=20, unique=True)),
                ('label', models.CharField(help_text='Link text in the footer and page title', max_length=100, verbose_name='Footer label')),
                ('label_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer label (UZ)')),
                ('content', models.TextField(blank=True)),
                ('content_uz', models.TextField(blank=True, null=True, verbose_name='Content (UZ)')),
                ('is_active', models.BooleanField(default=False, help_text='Show the footer link and the page on the site', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Legal page',
                'verbose_name_plural': 'Legal pages',
                'ordering': ['id'],
            },
        ),
    ]
